<a href="https://colab.research.google.com/github/midleone/DI-Bootcamp/blob/main/week6/day1/ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

original_list = [3.14, 2.17, 0, 1, 2]

numpy_array = np.array(original_list, dtype=int)

print(numpy_array)

[3 2 0 1 2]


In [3]:

array_1d = np.arange(10)

print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
import numpy as np

array_1d = np.arange(1, 10)
array_3x3 = array_1d.reshape(3, 3)

print(array_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
random_array = np.random.rand(4, 5)

print(random_array)

[[0.38114551 0.68125837 0.84072357 0.67028687 0.80304639]
 [0.54026362 0.02319829 0.92999601 0.62867925 0.3811469 ]
 [0.57782108 0.8801139  0.81621829 0.28116614 0.23304013]
 [0.65511966 0.2320387  0.90785164 0.7622534  0.41111553]]


In [7]:
my_array = np.array([[10, 11, 12, 13, 14],
                     [20, 21, 22, 23, 24],
                     [30, 31, 32, 33, 34]])

second_row = my_array[1, :]

print(second_row)

[20 21 22 23 24]


In [8]:
original_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reversed_array = original_array[::-1]

print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


In [9]:
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array_sum = np.sum(my_array)
array_average = np.mean(my_array)

print("Sum:", array_sum, ", Average:", array_average)

Sum: 55 , Average: 5.5


In [11]:
array_1d = np.arange(1, 21)
array_2d = array_1d.reshape(4, 5)

print(array_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_numbers = my_array[my_array % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]
